### ISSUE TITLE
Deleting custom fields - always deleting last one

### ISSUE THREAD

**Issue by pawcio-g** [intrip/laravel-authentication-acl#5]
I have just started playing with this package, but noticed that deleting custom fields does not work as expected - it does not matter which "-" icon I click to remove field, it always remove last custom field on the list. 

Let say I have added 3 custom fields and I decide I don't need first one, I cannot remove it as is removes last one.

**Comment by intrip** [comment]
It's fixed in version 1.1.2, update your composer.json and run composer update. Waiting for your feedback.

**Comment by pawcio-g** [comment]
Sorry, did not realized I am not using latest version - changed composer.json now and run composer update, I can see that 1.1.1 was removed and 1.1.2 installed, but I still experience the same issue?

**Comment by intrip** [comment]
I'll take a look at this and give you feedback, incase ill upload a fix.

**Comment by intrip** [comment]
Should be fixed now, wait a couple of minute then try to update the package and try it. Waiting for your feedback. Thanks.

**Comment by pawcio-g** [comment]
Sorry I did not have time to test it but I done that now and it seems to be working fine now, thanks!

**Comment by intrip** [comment]
You're welcome, anytime.
